language: python
python: 
  - "3.9"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - python setup.py -q install
script:
  - coverage run -m unittest discover
after_success:
  - coveralls
