os: linux
language: python
python: 
  - "3.9"
services:
  - mysql
before_install:
  - python -m pip install --upgrade pip
install:
  - xargs -a requirements.txt -n 1 pip install
  - python setup.py -q install
script:
  - cd department-app
  - export testing=1
  - coverage run --source=. --omit '*/venv/*' -m unittest
after_success:
  - coveralls
